function AboutPage(){
    return(
      <div className="text-cernter p-10"> 
        <h1 className="text-2xl font-bold my-4">AboutPage</h1>
        <p className="text-gray-300">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione tempora velit atque vel reprehenderit provident aut quas id odit, maiores esse, distinctio qui. Eligendi nisi iste velit doloremque saepe vitae quidem omnis modi dolorum. Aperiam assumenda mollitia molestias nostrum non. Facere nihil quasi nulla assumenda suscipit aliquam sed a, natus officia animi repellat aut. In minus vitae quisquam voluptatibus rem, dignissimos sed voluptas suscipit nisi facere enim. Ut, saepe harum suscipit commodi distinctio modi reprehenderit est beatae explicabo doloremque voluptatum molestiae itaque repellat eaque voluptate eveniet fugiat necessitatibus. Porro ipsum consequatur cum quibusdam, quia accusamus vel est tenetur enim architecto impedit velit voluptatibus libero! Doloribus distinctio cupiditate magni illum veritatis eius obcaecati suscipit aliquid inventore cumque, esse repudiandae laboriosam totam quos dolorem aperiam libero laborum! Totam expedita, perferendis accusamus numquam omnis tempore iure modi! Voluptas nesciunt blanditiis fuga laboriosam! Hic corrupti eum quisquam dolores deserunt amet ratione quam officiis animi sint impedit voluptate iusto saepe eos, aliquam voluptates, velit officia tenetur optio fuga maxime culpa repudiandae! Quaerat eaque eum quasi voluptatibus non neque soluta ducimus ipsam minima delectus cumque consequatur, quia voluptates ea. Sint earum ut a voluptatum tenetur voluptatem error temporibus beatae perspiciatis commodi id sunt dolore maxime molestiae exercitationem, fugiat perferendis, nemo laudantium dicta dolor ex suscipit. Minus tempora at quidem repellat, quos adipisci ipsum nihil impedit optio magnam vel corporis maiores incidunt, quisquam fugiat ex neque eligendi aut quis consequuntur. Ipsa, pariatur quae iure debitis laborum nesciunt, laudantium voluptas sint reiciendis reprehenderit libero laboriosam? Repellat sed perspiciatis omnis cum pariatur autem earum possimus, repellendus voluptas ipsum rerum aliquam accusantium ipsa numquam facere qui aliquid voluptatum, deserunt nesciunt suscipit, eaque quis! Quod corporis repellendus eum laboriosam reprehenderit eius incidunt veritatis recusandae vel nam fugiat quia corrupti error cum pariatur quidem dolor quo labore, ipsa sapiente modi, eveniet atque.
        </p>
        </div>
    )
  }
  export default AboutPage